server:
  grpc_port: 50051
  udp_port_start: 10000
  udp_port_end: 20000
  public_ip: "127.0.0.1"

dtls:
  cert_file: "./certs/cert.pem"
  key_file: "./certs/key.pem"

ai:
  enabled: false
  vad_sensitivity: 2
  summary_interval_min: 5
